---
title: "Reshape"
author: "shuxin dong"
date: "2023-11-29"
output: html_document
---

Let's put this up to github!

```{r}
library(tidyverse)
```

```{r}
gdp <- read_delim("../../../../Downloads/oecd-gdp.csv.bz2")
gdp %>% 
  head()
```
```{r}
gdpLong <- 
  gdp %>% 
  pivot_longer(!c(country, indicator))
gdpLong %>% 
  head(10)
```

```{r}
gdpLong <- 
  gdp %>% 
  pivot_longer(!c(country, indicator),
               names_to = "year",
               values_to = "gdp")
gdpLong %>% 
  head(10)
```

```{r}
gdpLong <- 
  gdp %>% 
  pivot_longer(!c(country, indicator),
               names_to = "year",
               values_to = "gdp") %>% 
  mutate(year = as.numeric(year))
gdpLong %>% 
  head(10)
```

```{r}
p <- data.frame(pregnancy = c("Yes", "No"),
                male = c(NA, 25),
                female = c(11, 18))
p
```

## change to longer form

```{r}
pl <- p %>% 
  pivot_longer(c(male, female),
             names_to = "sex",
             values_to = "count")
pl
```

## back to wider form

```{r}
pl %>% 
  pivot_wider(id_cols = pregnancy,
              names_from = sex,
              values_from = count)
```























